const API_FAILURE = 'API_FAILURE';
const API_START = 'API_START';

const GET_MY_PAYSLIPS = 'GET_MY_PAYSLIPS';
const GET_SALARY_DETAIL = 'GET_SALARY_DETAIL';
const GET_STAFF_PAYSLIPS = 'GET_SAFF_PAYSLIPS';

export {
  API_FAILURE,
  API_START,
  GET_MY_PAYSLIPS,
  GET_SALARY_DETAIL,
  GET_STAFF_PAYSLIPS,
};
