const API_FAILURE = 'API_FAILURE';
const API_START = 'API_START';

const GET_ALBUMS = 'GET_ALBUMS';
const ALBUM_DELETE = 'ALBUM_DELETE';
const ALBUM_ADD = 'ALBUM_ADD';
const ALBUM_EDIT = 'ALBUM_EDIT';
const REMOVE_IMAGES = 'REMOVES_IMAGES';

export {
  API_FAILURE,
  API_START,
  GET_ALBUMS,
  ALBUM_DELETE,
  ALBUM_ADD,
  ALBUM_EDIT,
  REMOVE_IMAGES,
};
