const FileTypes = {
  Event: 1,
  Holiday: 2,
};

const AttachmentTypes = {
  //Upload attachment
  UPLOAD_ATTACHMENT_EVENT: 1,
  UPLOAD_ATTACHMENT_ANNOUNCEMENT: 2,
  UPLOAD_ATTACHMENT_REQUEST: 3,
  UPLOAD_ATTACHMENT_TASK_UPLOAD: 4,
  UPLOAD_ATTACHMENT_LEAVE: 5,
  UPLOAD_ATTACHMENT_REQUEST_REPLY: 6,
  UPLOAD_FILE_TYPE_ALBUM: 7,
  UPLOAD_FILE_TYPE_SUPPORT_TICKET: 9,
  UPLOAD_FILE_TYPE_DOCUMENT_BIRTH: 10,
  UPLOAD_FILE_TYPE_DOCUMENT_MARRIAGE: 11,
  UPLOAD_FILE_TYPE_DOCUMENT_BIRTH_CERTIFICATE: 12,
  UPLOAD_FILE_TYPE_DOCUMENT_CERTIFICATE: 13,
  UPLOAD_FILE_TYPE_DOCUMENT_BIR: 14,
  UPLOAD_FILE_TYPE_DOCUMENT_MEDICAL: 15,
  UPLOAD_FILE_TYPE_DOCUMENT_GOVERNMENT: 16,
  UPLOAD_FILE_TYPE_DOCUMENT_NBI: 17,
};

export {FileTypes, AttachmentTypes};
