const API_FAILURE = 'API_FAILURE';
const API_START = 'API_START';

const FILE_GET = 'FILE_GET';
const FILE_ADD = 'FILE_ADD';
const FILE_EDIT = 'FILE_EDIT';
const FILE_DELETE = 'FILE_DELETE';
const FILE_REMOVE_IMAGES = 'FILE_REMOVE_IMAGES';
const FILE_UPLOAD_PROGRESS = 'FILE_UPLOAD_PROGRESS';
const DOWNLOAD_FILE = 'DOWNLOAD_FILE';
const GET_DOCUMENT = 'GET_DOCUMENT';
const DELETE_DOCUMENT = 'DELETE_DOCUMENT';

export {
  API_FAILURE,
  API_START,
  FILE_GET,
  FILE_ADD,
  FILE_EDIT,
  FILE_DELETE,
  FILE_REMOVE_IMAGES,
  FILE_UPLOAD_PROGRESS,
  DOWNLOAD_FILE,
  GET_DOCUMENT,
  DELETE_DOCUMENT,
};
