const API_FAILURE = 'API_FAILURE';
const API_START = 'API_START';

const HOME_GET = 'HOME_GET';
const HOME_DETAIL = 'HOME_DETAIL';
const HOME_UPDATE = 'HOME_UPDATE';
const HOME_DELETE = 'HOME_DELETE';
const HOME_ADD = 'HOME_ADD';

export {
  API_FAILURE,
  API_START,
  HOME_GET,
  HOME_DETAIL,
  HOME_UPDATE,
  HOME_DELETE,
  HOME_ADD,
};
