const API_FAILURE = 'API_FAILURE';
const API_START = 'API_START';

const GET_MY_OCCURRENCES = 'GET_MY_OCCURRENCES';
const OCCURRENCE_DETAIL = 'OCCURRENCE_DETAIL';
const DELETE_OCCURRENCE = 'DELETE_OCCURRENCE';
const ADD_OCCURRENCE = 'ADD_OCCURRENCE';
const GET_STAFF_OCCURRENCES = 'GET_STAFF_OCCURRENCES';
const REJECT_OCCURRENCE = 'REJECT_OCCURRENCE';
const APPROVE_OCCURRENCE = 'APPROVE_OCURRENCE';

export {
  API_FAILURE,
  API_START,
  GET_MY_OCCURRENCES,
  OCCURRENCE_DETAIL,
  DELETE_OCCURRENCE,
  ADD_OCCURRENCE,
  GET_STAFF_OCCURRENCES,
  REJECT_OCCURRENCE,
  APPROVE_OCCURRENCE,
};
