const API_FAILURE = 'API_FAILURE';
const API_START = 'API_START';

const GET_MY_LEAVES = 'GET_MY_LEAVES';
const GET_DASHBOARD_LEAVES = 'GET_DASHBOARD_LEAVES';
const GET_MY_BALANCE = 'GET_MY_BALANCE';
const APPLY_LEAVE = 'APPLY_LEAVE';
const LEAVE_DETAIL = 'LEAVE_DETAIL';
const CANCEL_LEAVE = 'CANCEL_LEAVE';
const UPDATE_LEAVE = 'UPDATE_LEAVE';
const GET_STAFF_LEAVES = 'GET_STAFF_LEAVES';
const STAFF_LEAVE_DETAIL = 'STAFF_LEAVE_DETAIL';
const APPROVE_LEAVE = 'APPROVE_LEAVE';
const REJECT_LEAVE = 'REJECT_LEAVE';
const APPLY_STAFF_LEAVE = 'APPLY_STAFF_LEAVE';
const COMPUTE_TOTAL_DAYS = 'COMPUTE_TOTAL_DAYS';
const UPDATE_STAFF_LEAVE = 'UPDATE_STAFF_LEAVE';

export {
  API_FAILURE,
  API_START,
  GET_MY_LEAVES,
  GET_MY_BALANCE,
  APPLY_LEAVE,
  LEAVE_DETAIL,
  CANCEL_LEAVE,
  UPDATE_LEAVE,
  GET_STAFF_LEAVES,
  STAFF_LEAVE_DETAIL,
  APPROVE_LEAVE,
  REJECT_LEAVE,
  APPLY_STAFF_LEAVE,
  COMPUTE_TOTAL_DAYS,
  UPDATE_STAFF_LEAVE,
  GET_DASHBOARD_LEAVES,
};
