const API_FAILURE = 'API_FAILURE';
const API_START = 'API_START';

const GET_MY_DASHBOARD = 'GET_MY_DASHBOARD';
const EMERGENCY_CALL = 'EMERGENCY_CALL';
const GET_CONTENTS = 'GET_CONTENTS';
const UPDATE_PROFILE = 'UPDATE_PROFILE';

export {
  API_FAILURE,
  API_START,
  GET_MY_DASHBOARD,
  EMERGENCY_CALL,
  GET_CONTENTS,
  UPDATE_PROFILE,
};
