const API_FAILURE = 'API_FAILURE';
const API_START = 'API_START';

const GET_MY_TIMESHEETS = 'GET_MY_TIMESHEETS';
const GET_MY_DETAIL_TIMESHEET = 'GET_MY_DETAIL_TIMESHEET';
const GET_COMPANY_PERIOD = 'GET_COMPANY_PERIOD';
const SUBMIT_TIMESHEET = 'SUBMIT_TIMESHEET';
const GET_CHECKINS = 'GET_CHECKINS';
const UPDATE_CHECKOUT = 'UPDATE_CHECKOUT';
const UPDATE_TASK = 'UPDATE_TASK';
const CHECKIN = 'CHECKIN';
const CHECKOUT = 'CHECKOUT';
const SUBMIT_REASON = 'SUBMIT_REASON';
const GET_STAFF_TIMESHEETS = 'GET_STAFF_TIMESHEETS';
const GET_COMPANY_EMPLOYEE = 'GET_COMPANY_EMPLOYEE';
const GET_STAFF_DETAIL_TIMESHEET = 'GET_STAFF_DETAIL_TIMESHEET';
const APPROVE_TIMESHEET = 'APPROVE_TIMESHEET';
const APPROVE_REJECT_DAY = 'APPROVE_REJECT_DAY';
const GET_DAILY_DETAILS = 'GET_DAILY_DETAILS';
const GET_TIMESHEET_DETAIL_FROM_NOTIFICATION =
  'GET_TIMESHEET_DETAIL_FROM_NOTIFICATION';

export {
  API_FAILURE,
  API_START,
  GET_MY_TIMESHEETS,
  GET_MY_DETAIL_TIMESHEET,
  GET_COMPANY_PERIOD,
  SUBMIT_TIMESHEET,
  GET_CHECKINS,
  UPDATE_CHECKOUT,
  UPDATE_TASK,
  CHECKIN,
  CHECKOUT,
  SUBMIT_REASON,
  GET_STAFF_TIMESHEETS,
  GET_COMPANY_EMPLOYEE,
  GET_STAFF_DETAIL_TIMESHEET,
  APPROVE_TIMESHEET,
  APPROVE_REJECT_DAY,
  GET_DAILY_DETAILS,
  GET_TIMESHEET_DETAIL_FROM_NOTIFICATION,
};
