const API_FAILURE = 'API_FAILURE';
const API_START = 'API_START';

const GET_HOLIDAYS = 'GET_HOLIDAYS';
const ADD_HOLIDAY = 'ADD_HOLIDAY';
const DELETE_HOLIDAY = 'DELETE_HOLIDAY';
const UPDATE_HOLIDAY = 'UPDATE_HOLIDAY';

export {
  API_FAILURE,
  API_START,
  GET_HOLIDAYS,
  ADD_HOLIDAY,
  DELETE_HOLIDAY,
  UPDATE_HOLIDAY,
};
