const API_FAILURE = 'API_FAILURE';
const API_START = 'API_START';

const GET_MY_REQUESTS = 'GET_MY_REQUESTS';
const DELETE_REQUEST = 'DELETE_REQUEST';
const ADD_REQUEST = 'ADD_REQUEST';
const UPDATE_REQUEST = 'UPDATE_REQUEST';
const INCOMING_REQUESTS = 'INCOMING_REQUESTS';
const OUTGOING_REQUESTS = 'OUTGOING_REQUESTS';
const ACCEPT_REQUEST = 'ACCEPT_REQUEST';
const DECLINE_REQUEST = 'DECLINE_REQUEST';
const REPLY_REQUEST = 'REPLY_REQUEST';

export {
  API_FAILURE,
  API_START,
  GET_MY_REQUESTS,
  DELETE_REQUEST,
  ADD_REQUEST,
  UPDATE_REQUEST,
  INCOMING_REQUESTS,
  OUTGOING_REQUESTS,
  ACCEPT_REQUEST,
  DECLINE_REQUEST,
  REPLY_REQUEST,
};
