const API_FAILURE = 'API_FAILURE';
const API_START = 'API_START';

const SUPPORT_GET = 'SUPPORT_GET';
const SUPPORT_DETAIL = 'SUPPORT_DETAIL';
const SUPPORT_COMMENT_GET = 'SUPPORT_COMMENT_GET';
const SUPPORT_REPLY = 'SUPPORT_REPLY';
const SUPPORT_DELETE = 'SUPPORT_DELETE';
const SUPPORT_ADD = 'SUPPORT_ADD';
const SUPPORT_UPLOAD = 'SUPPORT_UPLOAD';

export {
  API_FAILURE,
  API_START,
  SUPPORT_GET,
  SUPPORT_DETAIL,
  SUPPORT_COMMENT_GET,
  SUPPORT_REPLY,
  SUPPORT_DELETE,
  SUPPORT_ADD,
  SUPPORT_UPLOAD,
};
