const API_FAILURE = 'API_FAILURE';
const API_START = 'API_START';

const FORMS_GET = 'FORMS_GET';
const BLOCKS_GET = 'BLOCKS_GET';
const FIELDS_GET = 'FIELDS_GET';
const APPLICATION_GET = 'APPLICATION_GET';
const APPLICATION_SUBMIT = 'APPLICATION_SUBMIT';
const APPLICATION_DETAIL = 'APPLICATION_DETAIL';

const USER_LOGIN = 'USER_LOGIN';
const USER_LOGOUT = 'USER_LOGOUT';
const PASSWORD_CHANGE = 'PASSWORD_CHANGE';
const OTP_VERIFY = 'OTP_VERIFY';
const OTP_RESEND = 'OTP_RESEND';
const MOBILE_UPDATE = 'MOBILE_UPDATE';
const PASSWORD_SET = 'PASSWORD_SET';
const PASSWORD_FORGOT = 'PASSWORD_FORGOT';
const APPLICATION_DRAFT = 'APPLICATION_DRAFT';
const EMPTY_APPLICATION = 'EMPTY_APPLICATION';
const APPLICATION_COMMENT_ADD = 'APPLICATION_COMMENT_ADD';
const REMOVE_PHOTO = 'REMOVE_PHOTO';

export {
  API_FAILURE,
  API_START,
  FORMS_GET,
  BLOCKS_GET,
  FIELDS_GET,
  APPLICATION_GET,
  APPLICATION_SUBMIT,
  APPLICATION_DETAIL,
  USER_LOGIN,
  USER_LOGOUT,
  PASSWORD_CHANGE,
  OTP_RESEND,
  OTP_VERIFY,
  MOBILE_UPDATE,
  PASSWORD_SET,
  PASSWORD_FORGOT,
  APPLICATION_DRAFT,
  EMPTY_APPLICATION,
  APPLICATION_COMMENT_ADD,
  REMOVE_PHOTO,
};
