const API_FAILURE = 'API_FAILURE';
const API_START = 'API_START';

const USER_REGISTER = 'USER_REGISTER';
const OTP_VERIFY = 'OTP_VERIFY';
const OTP_RESEND = 'OTP_RESEND';
const MOBILE_UPDATE = 'MOBILE_UPDATE';
const PHOTO_UPLOAD = 'UPLOAD_PHOTO';
const TAG_ADD = 'ADD_TAG';
const USER_LOGIN = 'USER_LOGIN';
const USER_LOGOUT = 'USER_LOGOUT';
const USER_EDIT = 'USER_EDIT';
const USER_DELETE = 'USER_DELETE';
const USER_DETAIL = 'USER_DETAIL';
const COMPANY_DOMAIN = 'COMPANY_DOMAIN';
const COUNTRY_GET = 'COUNTRY_GET';

const PASSWORD_SET = 'PASSWORD_SET';
const PASSWORD_FORGOT = 'PASSWORD_FORGOT';
const CATEGORY_GET = 'CATEGORY_GET';
const BLOCK_NUMBER = 'BLOCK_NUMBER';
const FLOOR_NUMBER = 'FLOOR_NUMBER';
const PASSWORD_CHANGE = 'PASSWORD_CHANGE';

const COMMON_FILE_UPLOAD = 'COMMON_FILE_UPLOAD';

export {
  API_FAILURE,
  API_START,
  USER_REGISTER,
  OTP_VERIFY,
  OTP_RESEND,
  MOBILE_UPDATE,
  PHOTO_UPLOAD,
  TAG_ADD,
  USER_LOGIN,
  USER_LOGOUT,
  USER_EDIT,
  USER_DELETE,
  USER_DETAIL,
  COMPANY_DOMAIN,
  COUNTRY_GET,
  COMMON_FILE_UPLOAD,
  PASSWORD_SET,
  PASSWORD_FORGOT,
  CATEGORY_GET,
  FLOOR_NUMBER,
  BLOCK_NUMBER,
  PASSWORD_CHANGE,
};
