const API_FAILURE = 'API_FAILURE';
const API_START = 'API_START';

const FAQ_GET = 'FAQ_GET';
const FEEDBACK_ADD = 'FEEDBACK_ADD';
const FEEDBACK_GET = 'FEEDBACK_GET';
const FEEDBACK_UPDATE = 'FEEDBACK_UPDATE';

const GET_MY_ADS = 'GET_MY_ADS';
const VIEW_MY_AD = 'VIEW_MY_AD';
const AD_STATISTICS = 'AD_STATISTICS';
const VIEW_AD = 'VIEW_AD';

export {
  API_FAILURE,
  API_START,
  FAQ_GET,
  FEEDBACK_ADD,
  FEEDBACK_GET,
  FEEDBACK_UPDATE,
  GET_MY_ADS,
  VIEW_MY_AD,
  AD_STATISTICS,
  VIEW_AD,
};
