const API_FAILURE = 'API_FAILURE';
const API_START = 'API_START';

const GET_ANNOUNCEMENTS_PUBLISHED = 'GET_ANNOUNCEMENTS_PUBLISHED';
const GET_ANNOUNCEMENTS_UPCOMING = 'GET_ANNOUNCEMENTS_UPCOMING';
const ADD_ANNOUNCEMENT = 'ADD_ANNOUNCEMENT';
const DELETE_ANNOUNCEMENT = 'DELETE_ANNOUNCEMENT';
const UPDATE_ANNOUNCEMENT = 'UPDATE_ANNOUNCEMENT';

export {
  API_FAILURE,
  API_START,
  GET_ANNOUNCEMENTS_UPCOMING,
  GET_ANNOUNCEMENTS_PUBLISHED,
  ADD_ANNOUNCEMENT,
  DELETE_ANNOUNCEMENT,
  UPDATE_ANNOUNCEMENT,
};
