const API_FAILURE = 'API_FAILURE';
const API_START = 'API_START';

const GET_TODAY_EVENT = 'GET_TODAY_EVENT';
const EVENT_DETAIL = 'EVENT_DETAIL';
const GET_EVENT_ATTENDEE = 'GET_EVENT_ATTENDEE';
const GIVE_EVENT_ATTENDANCE = 'GIVE_EVENT_ATTENDANCE';
const DELETE_EVENT = 'DELETE_EVENT';
const GET_EVENTS = 'GET_EVENTS';
const ADD_EVENT = 'ADD_EVET';
const UPDATE_EVENT = 'UPDATE_EVENT';

export {
  API_FAILURE,
  API_START,
  GET_TODAY_EVENT,
  EVENT_DETAIL,
  GET_EVENT_ATTENDEE,
  GIVE_EVENT_ATTENDANCE,
  DELETE_EVENT,
  GET_EVENTS,
  ADD_EVENT,
  UPDATE_EVENT,
};
