const API_FAILURE = 'API_FAILURE';
const API_START = 'API_START';

const NOTIFICATION_GET = 'NOTIFICATION_GET';
const MARK_NOTIFICATION_READ = 'MARK_NOTIFICATION_READ';
const GET_HOME_NOTIFICATIONS = 'GET_HOME_NOTIFICATIONS';

export {
  API_FAILURE,
  API_START,
  NOTIFICATION_GET,
  MARK_NOTIFICATION_READ,
  GET_HOME_NOTIFICATIONS,
};
