const API_FAILURE = 'API_FAILURE';
const API_START = 'API_START';

const GET_USERS = 'GET_USERS';
const GET_USER_DROPDOWN = 'GET_USER_DROPDOWN';
const GET_PERSONAL_DROPDOWN = 'GET_PERSONAL_DROPDOWN';
const GET_SHIFT_DROPDOWN = 'GET_SHIFT_DROPDOWN';
const ADD_MEMBER = 'ADD_MEMBER';
const EDIT_MEMBER = 'EDIT_MEMBER';
const GET_ADDRESS = 'GET_ADDRESS';
const UPDATE_ADDRESS = 'UPDATE_ADDRESS';
const GET_JOB = 'GET_JOB';
const UPDATE_JOB = 'UPDATE_JOB';
const GET_DESIGNATION = 'GET_DESIGNATION';
const GET_DEPARTMENT = 'GET_DEPARTMENT';
const GET_SALARY = 'GET_SALARY';
const UPDATE_SALARY = 'UPDATE_SALARY';
const GET_BANK = 'GET_BANK';
const UPDATE_BANK = 'UPDATE_BANK';
const GET_FAMILY = 'GET_FAMILY';
const DELETE_FAMILY = 'DELETE_FAMILY';
const ADD_FAMILY = 'ADD_FAMILY';
const UPDATE_FAMILY = 'UPDATE_FAMILY';
const GET_LEAVE_DROPDOWN = 'GET_LEAVE_DROPDOWN';
const GET_LEAVE_INFO = 'GET_LEAVE_INFO';

export {
  API_FAILURE,
  API_START,
  GET_USERS,
  GET_USER_DROPDOWN,
  GET_PERSONAL_DROPDOWN,
  GET_SHIFT_DROPDOWN,
  ADD_MEMBER,
  EDIT_MEMBER,
  GET_ADDRESS,
  UPDATE_ADDRESS,
  GET_JOB,
  UPDATE_JOB,
  GET_DESIGNATION,
  GET_DEPARTMENT,
  GET_SALARY,
  UPDATE_SALARY,
  GET_BANK,
  UPDATE_BANK,
  GET_FAMILY,
  DELETE_FAMILY,
  ADD_FAMILY,
  UPDATE_FAMILY,
  GET_LEAVE_DROPDOWN,
  GET_LEAVE_INFO,
};
